name: "macro_insights"
version: "1.0"
config-version: 2
profile: "macro_insights"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  macro_insights:
    staging:
      +schema: stg          # -> macro_insights_stg
      +materialized: view   # staging always VIEW
    marts:
      +schema: mart         # -> macro_insights_mart
      +materialized: table  # marts as TABLE (fast for BI)
seeds:
  macro_insights:
    +schema: seed          # -> schema macro_insights_seed
    +quote_columns: false
