name: "macro_insights"
version: "1.0"
config-version: 2

profile: "macro_insights"

models:
  macro_insights:
    # ---- Staging layer (views) in a dedicated schema ----
    staging:
      +schema: macro_insights_stg
      +materialized: view

    # ---- Marts layer (tables) in a dedicated schema ----
    marts:
      +schema: macro_insights_mart
      +materialized: table

seeds:
  # ---- Seed data goes to its own schema ----
  +schema: macro_insights_seed
  +quote_columns: false