version: 2

models:
  - name: fct_gdp_yoy
    description: >
      GDP YoY fact table:
      per-country previous-year GDP and YoY percent change.
      yoy_pct is a fraction (e.g. 0.05 = +5%).
    columns:
      - name: country_code
        description: ISO country code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_gdp')
                field: country_code
      - name: year
        description: Calendar year
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 2010
                max_value: 2025
      - name: gdp_usd_bn
        description: GDP current year (USD bn)
      - name: gdp_prev
        description: Previous year GDP (USD bn)
      - name: yoy_pct
        description: Year-over-year GDP growth (fraction, -1..10 allowed for edge cases)
        # tests: handled by custom SQL test 'yoy_pct_bounds.sql'