macro_insights:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CH_HOST') }}"
      port: 8443
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASSWORD') }}"
      schema: "{{ env_var('CH_DATABASE', 'macro_insights') }}"
      secure: true
      verify: false
      threads: 4