macro_insights:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CH_HOST') }}"
      port: 8443
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASSWORD') }}"
      secure: true
      verify: true
      schema: "{{ env_var('CH_SCHEMA', 'macro_insights') }}"
      threads: 1