version: 2

models:
  - name: stg_gdp
    description: "Staging model for GDP data loaded from seed (gdp.csv)."
    columns:
      - name: country_code
        description: "2–3 letter country code (uppercase)."
        tests:
          - not_null

      - name: country_name
        description: "Human-readable country name."
        tests:
          - not_null

      - name: year
        description: "Year of GDP observation."
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 2010
                max_value: 2025

      - name: gdp_usd_bn
        description: "GDP in billions of USD."
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: ['country_code', 'year']