version: 2

models:
  - name: stg_gdp
    description: >
      Staging layer for country GDP time series (USD billions).
      Source: seed/S3 raw layer → normalized for marts consumption.
    columns:
      - name: country_code
        description: ISO country code (two or three letters)
        tests:
          - not_null
      - name: country_name
        description: Country name (English)
        tests:
          - not_null
      - name: year
        description: Calendar year (YYYY)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 2010
                max_value: 2025
      - name: gdp_usd_bn
        description: Nominal GDP in billions of USD
        tests:
          - not_null

# Custom data tests (SQL files in dbt/tests/)
tests:
  - name: non_negative_gdp
    description: Ensure GDP values are non-negative
    config:
      severity: error