name: dbt CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/dbt/.ci
      CH_HOST: ${{ secrets.CH_HOST }}
      CH_USER: ${{ secrets.CH_USER }}
      CH_PASSWORD: ${{ secrets.CH_PASSWORD }}
      CH_SCHEMA: ${{ secrets.CH_SCHEMA }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core==1.10.13" "dbt-clickhouse==1.9.3" dbt-utils

      - run: dbt --version

      - name: dbt deps
        working-directory: dbt
        run: dbt deps

      - name: dbt parse
        working-directory: dbt
        run: dbt parse

      - name: dbt seed
        working-directory: dbt
        run: dbt seed

      - name: dbt run
        working-directory: dbt
        run: dbt run

      - name: dbt test
        working-directory: dbt
        run: dbt test
