name: dbt CI

on:
  push:
    branches: [ main ]
    paths:
      - 'dbt/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'dbt/**'
      - '.github/workflows/ci.yml'

concurrency:
  group: dbt-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dbt:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/dbt/.ci
      CH_HOST: ${{ secrets.CH_HOST }}
      CH_USER: ${{ secrets.CH_USER }}
      CH_PASSWORD: ${{ secrets.CH_PASSWORD }}
      CH_SCHEMA: ${{ secrets.CH_SCHEMA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dbt (pinned versions)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core==1.10.13" "dbt-clickhouse==1.9.3"
          dbt --version

      - name: dbt deps
        working-directory: dbt
        run: dbt deps

      - name: dbt parse
        working-directory: dbt
        run: dbt parse

      - name: dbt seed
        working-directory: dbt
        run: dbt seed

      - name: dbt run
        working-directory: dbt
        run: dbt run

      - name: dbt test
        working-directory: dbt
        run: dbt test

      - name: Upload dbt artifacts (target/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-target
          path: dbt/target/
          retention-days: 7